Adding post aws token example
Fieldwire/fieldwire_ruby_sample pull request #1
Opened 2018-06-12 17:26 UTC by NicolasFieldwire

2018-06-14 23:20 UTC, skalb requested changes

2018-06-14 23:20 UTC, skalb commented on fieldwire.rb
> +def postToAws(url, attributes, filename)
post_to_aws

2018-06-14 23:20 UTC, skalb commented on fieldwire.rb
> +require 'rest-client'
Do we need both HTTParty and RestClient? Can we just use RestClient?

2018-06-15 00:23 UTC, NicolasFieldwire commented on fieldwire.rb
> +def postToAws(url, attributes, filename)
Done

2018-06-15 00:23 UTC, NicolasFieldwire commented on fieldwire.rb
> +require 'rest-client'
Yes. Done.

2018-06-15 00:39 UTC, skalb requested changes

2018-06-15 00:39 UTC, skalb commented on Gemfile
> +gem 'httparty', '0.14.0'
Can't we remove this dependency now?

2018-06-15 00:51 UTC, NicolasFieldwire commented
Sure.

On Thu, Jun 14, 2018 at 5:40 PM, Sameer Kalburgi <notifications@github.com>
wrote:

> *@skalb* requested changes on this pull request.
> ------------------------------
>
> In Gemfile
> <https://github.com/Fieldwire/fieldwire_ruby_sample/pull/1#discussion_r195609665>
> :
>
> > \ No newline at end of file
> +gem 'httparty', '0.14.0'
>
> Can't we remove this dependency now?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Fieldwire/fieldwire_ruby_sample/pull/1#pullrequestreview-129014644>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AhmtRiXekYkdeZG9MzRlAaVnLHRqJXy6ks5t8wJggaJpZM4Uk2Bw>
> .
>

2018-06-15 00:57 UTC, skalb approved these changes

2018-06-15 00:58 UTC, merged